{% set name = "swisslandstats-geopy" %}
{% set version = "0.11.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: bd8a4a9e85ffea53d27584a05cc4328cca2e96aa4c6d5c4b3c7940bde42fa0b9

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - matplotlib >=2.2
    - numpy >=1.15
    - pandas >=0.17.0
    - python >=3.6
    - rasterio >=1.0.0
    - geopandas >=0.10.0
    - osmnx >=1.0.0
    - xarray

test:
  imports:
    - swisslandstats
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/martibosch/swisslandstats-geopy
  summary: Python for the Swiss Federal Statistics Geodata (GEOSTAT)
  license: GPL-3.0-or-later
  license_file: LICENSE.txt
  doc_url: https://swisslandstats-geopy.readthedocs.io/
  dev_url: https://github.com/martibosch/swisslandstats-geopy

extra:
  recipe-maintainers:
    - martibosch
